name: Fetch Data Daily

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Increment Build Action On README.md
      run: |
        # Increment the build in README.md
        current_build=$(grep -oP '(?<=Build: )\d+' README.md)
        new_build=$((current_build + 1))
        sed -i "s/Build: $current_build/Build: $new_build/" README.md
        echo "Build number is now: $new_build" >> README.md

    - name: Commit and push (if changed)
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -u
          git commit -m "Increment build to $new_build"
          git push
        else
          echo "No changes to commit."
        fi
