name: Fetch Data Daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  change_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Readme
        run: |
          echo "Last updated: $(date -u)" >> readme.md

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add readme.md
          git commit -m "Update readme with timestamp" || true
          git push
